--- # error handing example

- hosts: apacheweb
  connection: ssh
  gather_facts: no
  user: test
  sudo: yes
  tasks:
    - name: excutre a task that fails 
      command: /bin/false
      ignore_errors: yes
    - name: install telnet
      yum: pkg=telnet state=latest
 

