--- # htpasswd module
- hosts: apacheweb
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: install httpd
      yum: pkg=httpd state=latest
    - name: install python dependencies
      yum: pkg=python-passlib state=latest
    - name: adding teh user to website authentication
      htpasswd: path=/etc/httpd/.htpasswd name=test password=password owner=test group=test mode=0640

 
