--- # notify module
- hosts: apacheweb
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  tasks:
    - name: installed httpd
      yum: pkg=httpd state=latest
      notify: restart httpd
  handlers:
    - name: restart httpd
      action: service name=httpd state=restarted
