--- # wait for
- hosts: apacheweb
  connection: ssh
  user: test
  sudo: yes
  gather_facts: no
  tasks:
   - name: Install Apache tomcate
     yum: pkg=tomcat state=latest
   - name: waiting to 8080 to listen
     wait_for:
       port: 8080
       state: started
   - name: check lynx is installed
     yum: pkg=lynx state=latest

