- name: install httpd
  yum: name={{ redhat_apache }} state=latest
  when: ansible_os_family == 'RedHat' 
  ignore_errors: yes
  notify: restart httpd

- name: install apache2
  apt: name={{ debain_apache }} state=latest
  when: ansible_os_family == 'Debian'
  ignore_errors: yes
  notify: restart apache2

#- debug: need to install telnet
#  when: ansible_os_family == 'Debian'
#  notify: install telnet
