--- # Master playbook for web servers
- hosts: ubuntu:apacheweb
  user: test
  sudo: yes
  connection: ssh
  pre_tasks:
    - name: When did the role start
      raw: date > /home/test/startofrole.log
  roles:
   #- webservers
   # Conditional Include Statements
    - { role: redhat_webservers, when: "ansible_os_family == 'Redhat'" }
    - { role: debian_webservers, when: "ansible_os_family == 'Debain'" }
  post_tasks:
    - name: When did the role ended
      raw: date > /home/test/endofrole.log
